name: Setup Gradle
description: Sets up the environment to run Gradle

inputs:
  gradle-jvm-args:
    description: "JVM args to pass to Gradle"
    required: true
    default: "-Xmx1g -XX:+UseParallelGC -Dfile.encoding=UTF-8"

runs:
  using: composite

  steps:
    - uses: actions/setup-java@v3
      with:
        distribution: "zulu"
        java-version: 17

    - name: Write Gradle build properties to local `gradle.properties`
      run: |
        mkdir -p ~/.gradle
        printf "org.gradle.jvmargs=${{ inputs.gradle-jvm-args }}\n" >> ~/.gradle/gradle.properties
        printf "org.gradle.vfs.watch=false\n" >> ~/.gradle/gradle.properties
      shell: bash

    - uses: gradle/gradle-build-action@v2
      with:
        gradle-home-cache-cleanup: true
