name: Validate

on:
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  gradle-wrapper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: gradle/wrapper-validation-action@v1

  core-checks:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project: ["lottie", "lottie-compose"]
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup-gradle-build

      - run: ./gradlew :${{ matrix.project }}:assemble

      - run: ./gradlew :${{ matrix.project }}:check

      - run: ./gradlew :${{ matrix.project }}:publishToMavenLocal

      - name: Upload lint reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: lint_reports
          path: |
            **/reports/lint-results-*.xml
            **/reports/lint-results-*.html

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: unit_test_reports
          path: "**/reports/tests"

  sample-apps-check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project: ["sample", "sample-compose", "issue-repro", "issue-repro-compose"]
        task: ["assemble", "check", "assembleDebugAndroidTest"]
    name: "run: :${{ matrix.project }}:${{ matrix.task}}"
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup-gradle-build

      - run: ./gradlew :${{ matrix.project }}:${{ matrix.task}}

  snapshot-tests:
    if: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup env
        shell: bash
        run: |
          curl https://us-central1-lottie-snapshots.cloudfunctions.net/snapshot-env-v1/emulator > snapshot-env
          while read line; do
            echo "$line" >> $GITHUB_ENV
          done < snapshot-env

      - uses: ./.github/actions/setup-gradle-build

      - name: Build app
        run: ./gradlew snapshot-tests:assembleDebug snapshot-tests:assembleDebugAndroidTest

      - name: Run tests
        uses: emulator-wtf/run-tests@v0.9.6
        with:
          api-token: ${{ env.EW_API_TOKEN }}
          version: 0.9.19
          app: snapshot-tests/build/outputs/apk/debug/snapshot-tests-debug.apk
          test: snapshot-tests/build/outputs/apk/androidTest/debug/snapshot-tests-debug-androidTest.apk
          devices: |
            model=Pixel2,version=23,gpu=auto
            model=Pixel2,version=31,gpu=auto
          outputs-dir: build/test-results

      - name: Save PR number
        if: github.event_name == 'pull_request'
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          mkdir -p ./env
          echo PR_NUMBER=$PR_NUMBER > ./env/env
          echo GITHUB_SHA=${{ github.sha }} >> ./env/env
      - uses: actions/upload-artifact@v3
        with:
          name: env
          path: env/

  deploy:
    if: github.event_name == 'push' && github.repository == 'airbnb/lottie-android' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: [core-checks, gradle-wrapper, snapshot-tests]
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup-gradle-build

      - name: "Deploy Snapshot"
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        run: ./deploy_snapshot.sh
